### ISSUE TITLE
Question about reward learning

### ISSUE THREAD

**Issue by SatireY** [2toinf/DecisionNCE#3]
Great job!
I have a question about rewarding learning,Is the reward calculated directly by S(φ(on), ψ(l)) or S(φ(on+1), ψ(l)) − S(φ(on), ψ(l))? I noticed that the get_reward function of the model is calculated directly by S(φ(on), ψ(l)) and it is written in the appendix of the paper that it is calculated by S(φ(on+1), ψ(l)) − S(φ(on), ψ(l)). If it's calculated by  S(φ(on+1), ψ(l)) − S(φ(on), ψ(l)),Then how should the reward of the last step be calculated?

**Comment by 2toinf** [comment]
Thanks for your attention!
Indeed, you can choose the reward formulation according to the application scenario.
For MPPI, the reward is calculated by S(φ(on+1), ψ(l)) − S(φ(on), ψ(l)) as metioned in the paper as the relative differences can align the numerical scales between different trajectory. In this case, for a n-step trajectory we can get the full trajectory reward by adding up n-1 transiaction rewards. 
For reward visualization as shown in Fig.11,  you can simply use S(φ(on), ψ(l)) as the reward as it can also reflect the correct reward trends.

**Comment by 2toinf** [comment]
> Great job! I have a question about rewarding learning,Is the reward calculated directly by S(φ(on), ψ(l)) or S(φ(on+1), ψ(l)) − S(φ(on), ψ(l))? I noticed that the get_reward function of the model is calculated directly by S(φ(on), ψ(l)) and it is written in the appendix of the paper that it is calculated by S(φ(on+1), ψ(l)) − S(φ(on), ψ(l)). If it's calculated by S(φ(on+1), ψ(l)) − S(φ(on), ψ(l)),Then how should the reward of the last step be calculated?

Thanks for your attention!
Indeed, you can choose the reward formulation according to the application scenario. The relative differences calculated by S(φ(on+1), ψ(l)) − S(φ(on), ψ(l)) and the absolute similarity calculated by S(φ(on), ψ(l)) are interchangeable. 
For MPPI, the reward is calculated by S(φ(on+1), ψ(l)) − S(φ(on), ψ(l)) as metioned in the paper as the relative differences can align the numerical scales between different trajectory. In this case, for a n-step trajectory we can get the full trajectory reward by adding up n-1 transiaction rewards.
For reward visualization as shown in Fig.11, you can simply use S(φ(on), ψ(l)) as the reward as it can also reflect the correct reward trends. 
In the code, we implemente the get_reward function to calculate S(φ(on), ψ(l)) as it can be flexibly used to calculate the two forms of reward mentioned above.
